Testing chunking a single image in one step

diff --git a/.github/workflows/bootc.yaml b/.github/workflows/bootc.yaml
--- a/.github/workflows/bootc.yaml
+++ b/.github/workflows/bootc.yaml
@@ -31,96 +31,105 @@ jobs:
         with:
           ref: master
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-
-      - name: Log in to GitHub Container Registry
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v3
-        with:
-          context: .
-          push: true
-          tags: ghcr.io/${{ github.repository }}/bootc-base:latest
-          file: ./Containerfile
-          build-args: |
-              email=${{ secrets.EMAIL  }}
-              user=chris
-
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v3
-        with:
-          context: .
-          push: true
-          tags: ghcr.io/${{ github.repository }}/bootc-desktop:latest
-          file: ./Desktop.containerfile
-          build-args: |
-              email=${{ secrets.EMAIL  }}
-              user=chris
-
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v3
-        with:
-          context: .
-          push: true
-          tags: ghcr.io/${{ github.repository }}/bootc-thinkpad:latest
-          file: ./Thinkpad.containerfile
-          build-args: |
-              email=${{ secrets.EMAIL  }}
-              user=chris
+      # - name: Set up Docker Buildx
+      #   uses: docker/setup-buildx-action@v2
+      #
+      # - name: Log in to GitHub Container Registry
+      #   uses: docker/login-action@v2
+      #   with:
+      #     registry: ghcr.io
+      #     username: ${{ github.actor }}
+      #     password: ${{ secrets.GITHUB_TOKEN }}
+      #
+      # - name: Build and push Docker image
+      #   uses: docker/build-push-action@v3
+      #   with:
+      #     context: .
+      #     push: true
+      #     tags: ghcr.io/${{ github.repository }}/bootc-base:latest
+      #     file: ./Containerfile
+      #     build-args: |
+      #         email=${{ secrets.EMAIL  }}
+      #         user=chris
+      #
+      # - name: Build and push Docker image
+      #   uses: docker/build-push-action@v3
+      #   with:
+      #     context: .
+      #     push: true
+      #     tags: ghcr.io/${{ github.repository }}/bootc-desktop:latest
+      #     file: ./Desktop.containerfile
+      #     build-args: |
+      #         email=${{ secrets.EMAIL  }}
+      #         user=chris
+      #
+      # - name: Build and push Docker image
+      #   uses: docker/build-push-action@v3
+      #   with:
+      #     context: .
+      #     push: true
+      #     tags: ghcr.io/${{ github.repository }}/bootc-thinkpad:latest
+      #     file: ./Thinkpad.containerfile
+      #     build-args: |
+      #         email=${{ secrets.EMAIL  }}
+      #         user=chris
+      #
+      # - name: Cleanup build images
+      #   run: |
+      #     set -euxo pipefail
+      #     docker rmi ghcr.io/${{ github.repository }}/bootc-base:latest
+      #     docker rmi ghcr.io/${{ github.repository }}/bootc-desktop:latest
+      #     docker rmi ghcr.io/${{ github.repository }}/bootc-thinkpad:latest
 
       - name: Rechunk base
         run: |
           set -euxo pipefail
+          podman build -t localhost/bootc-base:latest .
           podman run --rm --privileged \
             -v $(pwd):/workspace \
             -w /workspace \
             quay.io/fedora/fedora-bootc:43 \
             rpm-ostree compose build-chunked-oci --bootc \
-            --from=ghcr.io/${{ github.repository }}/bootc-base:latest \
+            --from=localhost/bootc-base:latest \
             --output=oci-archive:bootc-base-chunked.tar \
             --format-version=2
           podman load -i bootc-base-chunked.tar
           podman tag localhost/bootc-base-chunked ghcr.io/${{ github.repository }}/bootc-base:chunked
           podman push ghcr.io/${{ github.repository }}/bootc-base:chunked
+          podman rmi localhost/bootc-base:latest ghcr.io/${{ github.repository }}/bootc-base:chunked
           rm bootc-base-chunked.tar
-
-      - name: Rechunk desktop
-        run: |
-          set -euxo pipefail
-          podman run --rm --privileged \
-            -v $(pwd):/workspace \
-            -w /workspace \
-            quay.io/fedora/fedora-bootc:43 \
-            rpm-ostree compose build-chunked-oci --bootc \
-            --from=ghcr.io/${{ github.repository }}/bootc-desktop:latest \
-            --output=oci-archive:bootc-desktop-chunked.tar \
-            --format-version=2
-          podman load -i bootc-desktop-chunked.tar
-          podman tag localhost/bootc-desktop-chunked ghcr.io/${{ github.repository }}/bootc-desktop:chunked
-          podman push ghcr.io/${{ github.repository }}/bootc-desktop:chunked
-          rm bootc-desktop-chunked.tar
-
-      - name: Rechunk thinkpad
-        run: |
-          set -euxo pipefail
-          podman run --rm --privileged \
-            -v $(pwd):/workspace \
-            -w /workspace \
-            quay.io/fedora/fedora-bootc:43 \
-            rpm-ostree compose build-chunked-oci --bootc \
-            --from=ghcr.io/${{ github.repository }}/bootc-thinkpad:latest \
-            --output=oci-archive:bootc-thinkpad-chunked.tar \
-            --format-version=2
-          podman load -i bootc-thinkpad-chunked.tar
-          podman tag localhost/bootc-thinkpad-chunked ghcr.io/${{ github.repository }}/bootc-thinkpad:chunked
-          podman push ghcr.io/${{ github.repository }}/bootc-thinkpad:chunked
-          rm bootc-thinkpad-chunked.tar
+      #
+      # - name: Rechunk desktop
+      #   run: |
+      #     set -euxo pipefail
+      #     podman run --rm --privileged \
+      #       -v $(pwd):/workspace \
+      #       -w /workspace \
+      #       quay.io/fedora/fedora-bootc:43 \
+      #       rpm-ostree compose build-chunked-oci --bootc \
+      #       --from=ghcr.io/${{ github.repository }}/bootc-desktop:latest \
+      #       --output=oci-archive:bootc-desktop-chunked.tar \
+      #       --format-version=2
+      #     podman load -i bootc-desktop-chunked.tar
+      #     podman tag localhost/bootc-desktop-chunked ghcr.io/${{ github.repository }}/bootc-desktop:chunked
+      #     podman push ghcr.io/${{ github.repository }}/bootc-desktop:chunked
+      #     rm bootc-desktop-chunked.tar
+      #
+      # - name: Rechunk thinkpad
+      #   run: |
+      #     set -euxo pipefail
+      #     podman run --rm --privileged \
+      #       -v $(pwd):/workspace \
+      #       -w /workspace \
+      #       quay.io/fedora/fedora-bootc:43 \
+      #       rpm-ostree compose build-chunked-oci --bootc \
+      #       --from=ghcr.io/${{ github.repository }}/bootc-thinkpad:latest \
+      #       --output=oci-archive:bootc-thinkpad-chunked.tar \
+      #       --format-version=2
+      #     podman load -i bootc-thinkpad-chunked.tar
+      #     podman tag localhost/bootc-thinkpad-chunked ghcr.io/${{ github.repository }}/bootc-thinkpad:chunked
+      #     podman push ghcr.io/${{ github.repository }}/bootc-thinkpad:chunked
+      #     rm bootc-thinkpad-chunked.tar
 
       - name: Log out from GitHub Container Registry
         run: podman logout ghcr.io
